version: "3.8"

services:
  backend:
    platform: linux/${TARGETARCH:-arm64}
    image: tykio/midsommar:latest
    volumes:
      - ./ai-studio.db:/app/ai-studio.db # Use bind mount for the repo file
    ports:
      - "8080:8080" # Frontend
      - "9090:9090" # Proxy
    environment:
      - TYK_AI_LICENSE=ADD_HERE
      - CHOKIDAR_USEPOLLING=true
      - ALLOW_REGISTRATIONS=true
      - SITE_URL=http://localhost:8080
      - FROM_EMAIL=noreply@tyk.io
      - DEVMODE=true
      - DEBUG_HTTP=false
      - DEBUG_HTTP_PROXY=false
      - DATABASE_URL=ai-studio.db # Ensure this matches the filename
      - DATABASE_TYPE=sqlite
      - ECHO_CONVERSATION=true
      - TYK_AI_SECRET_KEY=top-secret
      - DOCS_URL=http://localhost:8989
      - PROXY_URL=http://localhost:9090
      - FILTER_SIGNUP_DOMAINS=tyk.io
      - DEFAULT_SIGNUP_MODE="both"
      - TIB_ENABLED=true
    stdin_open: true
    tty: true